var GAME_LEVELS = [
  ["              xxx                            x    x                                                xxxxxxxx",
   "              xxx                            x    x                                                xxxxxxxx",
   "              xxx                            x    x                                                xxxxxxxx",
   "              xxx                  o  o      x    x                                                xxxxxxxx",
   "              xxx                  g  g     xxx   x                                           gg  #xxxxxxxx",
   "                         ##        x!!x     (((  xxx                                          xx  xxxxxxxxx",
   "               o       gggg   gggggxxxxgggg      (((  gg                                      xx   xxxxxxxx",
   "       gg     ggg     gxxxx  #xxxxxxxxxxxxx           xxo                           |     g   xx   xxxxxxxx",
   "       xx     xxx     xxxxx  xxxxxxxxxxxxxx           xxo                                 x   xx   xxxxxxxx",
   "       xx     xxx     xxxxx   xxxxxxxxxxxxx     o     xxo                                 x   xx#  xxxxxxxx",
   "       xx     xxx    gxxxxx#  xxxxxxxxxxxxxgggggggggggxxo                      o ### o    x   xxx  xxxxxxxx",
   "     ggxxg    xxx   gxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxx                 o    gg xxx gg   x   xx   xxxxxxxx",
   "     xxxxxg   xxx  gxxxxxxx    xxxxxxxxxxxxx  xxxxxx                    gg    x   x   x   x   xx   xxxxxxxx",
   "     xxxxxx   xxx  xxxxxxxx          xxxxxx    xxxxx               o    x     x | x   x   x   xx  gxxxxxxxx",
   "     xxxxx    xxx   xxxxxxx                                       gg || x     x!!!!!!!x   x   xx          x",
   "   ggxxxx     xxx    xxxxxx   o                      o       o    x     x     x!!!!!!!x   x   xx          x",
   "   xxxxxx    gxxxg    xxxxx   gg   gggggg o   o gggggggg     g    x     x  || x!!!!!!!x   x   xx          x",
   " @ xxxxxx  ogxxxxxgo  xxxxx         xxxxxgg!!gggxxxxxx       x    x     x     x!!!!!!!x   x   xx        o x",
   "gggxxxxxx!!gxxxxxxxg!!xxxxx!!!!!!!!!!xxxxxxxxxxxxxxxx        x || x     x     x!!!!!!!x   x   xx   gggggggx"],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  ggg           ",
   "                                                   gg      gg    gx!xg          ",
   "                                    o o      gg                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   ggggg                          xvx           ",
   "                                                                            gg  ",
   "  gg                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      ggggg                             o x  ",
   "  x          gggg       o                                                    x  ",
   "  x  @       xxxx                                                gxxxg       x  ",
   "  xggggggggggxxxxgggggggggggggg   gggggggggggggggggggg     ggggggxxxxxgggggggx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      g!!g                        ggggggg                                    g!g  ",
   "                                      x!!x                     gggx     xggg                                 x!x  ",
   "                                      x!!xggggggggg           gx           xg                                x!x  ",
   "                                      xx!!!!!!!!!!xg         gx             xg                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    gx!x  ",
   "                                                 x!x         x                                ggggggggggggggx!!x  ",
   "                                                 xvx         x     g   g                        !!!!!!!!!!!!!!xx  ",
   "                                                             xg  |   |   |  gg            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xg!!!!!!!!!!!gx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                               g     g            xxxxxxx        ggg         ggg                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xg        x                    ",
   "                                               xg    x                             x         x                    ",
   "                                               x     x      o  o     g   g         x         x                    ",
   "               ggggggg        ggg   ggg        x     x               x   x         x         x                    ",
   "              gxxxxxxxg         x   x          x     x     gggggg    x   x   xxxxxxxgg       x                    ",
   "             gxxxxxxxxxg        x o x          x    gx               x   x   x               x                    ",
   "     @       xxxxxxxxxxx        x   x          x     x               x   x   x               x                    ",
   "    ggg      xxxxxxxxxxx        x   x          x     x               x   xxxxx   gggggg      x                    ",
   "    xxx      xxxxxxxxxxx       gx o xg         x     x               x     o     x x         x                    ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!gx     xg!!!!!!!!xg    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xg  o o  gx                    ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!x    o                 gx!!!!!!xx !                    xg     gx                     ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!x                     gx!!!!!!xx  !                     xggxxxx                      ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!xg       gggggggggggxxx!!!!!!xx   !                                                  ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!xgggggggx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["              xxx                            x    x                                                xxxxxxxx",
   "              xxx                            x    x                                                xxxxxxxx",
   "              xxx                            x    x                                                xxxxxxxx",
   "              xxx                  o  o      x    x                                                xxxxxxxx",
   "              xxx                  g  g     xxx   x                                           gg  #xxxxxxxx",
   "                         ##        x!!x     (((  xxx                                          xx  xxxxxxxxx",
   "               o       gggg   gggggxxxxgggg      (((  gg                                      xx   xxxxxxxx",
   "       gg     ggg     gxxxx  #xxxxxxxxxxxxx           xxo                           |     g   xx   xxxxxxxx",
   "       xx     xxx     xxxxx  xxxxxxxxxxxxxx           xxo                                 x   xx   xxxxxxxx",
   "       xx     xxx     xxxxx   xxxxxxxxxxxxx     o     xxo                                 x   xx#  xxxxxxxx",
   "       xx     xxx    gxxxxx#  xxxxxxxxxxxxxgggggggggggxxo                      o ### o    x   xxx  xxxxxxxx",
   "     ggxxg    xxx   gxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxx                 o    gg xxx gg   x   xx   xxxxxxxx",
   "     xxxxxg   xxx  gxxxxxxx    xxxxxxxxxxxxx  xxxxxx                    gg    x   x   x   x   xx   xxxxxxxx",
   "     xxxxxx   xxx  xxxxxxxx          xxxxxx    xxxxx               o    x     x | x   x   x   xx  gxxxxxxxx",
   "     xxxxx    xxx   xxxxxxx                                       gg || x     x!!!!!!!x   x   xx          x",
   "   ggxxxx     xxx    xxxxxx   o                      o       o    x     x     x!!!!!!!x   x   xx          x",
   "   xxxxxx    gxxxg    xxxxx   gg   gggggg o   o gggggggg     g    x     x  || x!!!!!!!x   x   xx          x",
   " @ xxxxxx  ogxxxxxgo  xxxxx         xxxxxgg!!gggxxxxxx       x    x     x     x!!!!!!!x   x   xx        o x",
   "gggxxxxxx!!gxxxxxxxg!!xxxxx!!!!!!!!!!xxxxxxxxxxxxxxxx        x || x     x     x!!!!!!!x   x   xx   gggggggx"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        g                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       gxg                                                                    ",
   "                                       xxx                 !!!        !!!  ggg                                ",
   "                                       xxx                 !x!        !x!                                     ",
   "                                     gxxxxxg                x          x                                      ",
   "                                      xxxxx                 x   oooo   x       ggg                            ",
   "                                      xxxxx                 x          x      g!!!g                           ",
   "                                      xxxxx                 xggggggggggx       xxx                            ",
   "                                     gxxxxxg      g   g      x                                                ",
   "                                      xxxxxxggggggx   xggggggx              g g                               ",
   "                                      xxxxx           x                    g!!!g                              ",
   "                                      xxxxx           x                     xxx                               ",
   "                                     gxxxxxg          x                                                       ",
   "                                      xxxxx= = = =    x            ggg                                        ",
   "                                      xxxxx           x           g!!!g                                       ",
   "                                      xxxxx    = = = =x     o      xxx       ggg                              ",
   "                                     gxxxxxg          x                     g!!!g                             ",
   "                              o   o   xxxxx           x     g                xxv        ggg                   ",
   "                                      xxxxx           x              g                 g!!!g                  ",
   "                             ggg ggg gxxxxxg     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xgx x xxxxxxx          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   gggggggxxxxxxxxxxxxxxxx                                        ",
   "                             xg           gx                                         ggg                      ",
   "  ggg                         x     g     x                                         g!!!g                ggg  ",
   "  x x                         x    gxg    x                                          xxx                 x x  ",
   "  x                           x    xxx    xgggggg                        ggggg                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xg          x                              x g x                             x  ",
   "  x                                       x       |gggg|    |gggg|     ggx xgx                             x  ",
   "  x                ggg             o o    x                              x         ggg                     x  ",
   "  x               gxxxg       gg          x                             gxg       g!!!g          g         x  ",
   "  x               oxxxo       x    ggg    x                             xxx        xxx          gxg        x  ",
   "  x                xxx        xggggxxxggggx  g oo g    g oo g    g oo  gxxxg                    xxx        x  ",
   "  x      @          x         xxxxxxxxxxxxx!!x    x!!!!x    x!!!!x    gxxxxxg                    x      o  x  ",
   "  xgggggggggggggggggxgggggggggxxxxxxxxxxxxxxxxggggxxxxxxggggxxxxxxggggxxxxxxxgxxxgggggggxxxggggggxgggggggggx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  ggggg       ",
   "                                                                                                      x       ",
   "                                                                                                  ggggx       ",
   "                                                                                                  x           ",
   "                                                                                                  x ggg       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxgx x       ",
   "                   ggg                                                                                x       ",
   "       !  o  !                                                ggggg ggggg ggggg ggggg ggggg ggggg ggggx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            g                                   xgg x xgg x xgg x xgg x xgg x xgg x xgggg       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  gggx xgggx xgggx xgggx xgggx xgggx xgggggx       ",
   "                                                                                                              ",
   "          o              ggg                              gg                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      gg                                                      ",
   "                   ggg         ggg                                                                            ",
   "                                                                                                              ",
   "                          o                                                     g      g                      ",
   "                                                          gg     gg                                           ",
   "             ggg         ggg         ggg                                 g                  g                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  ggggggggggg                                                                                                 ",
   "  x         x o ggggggggg o ggggggggg o gg                                                g                   ",
   "  x         x   x       x   x       x   x                 ||                  g     g                         ",
   "  x  @      xgggx   o   xgggx   o   xgggx                                                                     ",
   "  xgggggg                                     ggggg       xx     xx     ggg                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                            ",
   "                                            ",
   "  x   x                                  x  ",
   "  x   x                                  x  ",
   "  x   x xxxxx x   x   x   x xxxxx x   x  x  ",
   "  xxxxx x   x x   x   x   x x   x xx  x  x  ",
   "    x   x   x x   x   x x x x   x x x x  x  ",
   "    x   x   x x   x   x x x x   x x  xx     ",
   "    x   xxxxx xxxxx   xxxxx xxxxx x   x  x  ",
   "                                            ",
   "                                            ",
   " @                                          ",
   "gggggggggggggggggggggggggggggggggggggggggggg"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
